# Generated by Django 5.2.5 on 2025-08-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consults", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("created_at",)},
        ),
        migrations.AddField(
            model_name="assessment",
            name="assistant_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_provider",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="session_length_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="status",
            field=models.CharField(default="generated", max_length=32),
        ),
        migrations.AddField(
            model_name="assessment",
            name="used_llm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consult",
            name="duration_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consult",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consult",
            name="use_llm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
