# Generated by Django 5.2.5 on 2025-09-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        (
            "consults",
            "0002_alter_message_options_assessment_assistant_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="consult",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consults",
                to="clients.client",
            ),
        ),
    ]
