# Generated by Django 5.2.5 on 2025-09-08 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("preferred_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("Under 18", "Under 18"),
                            ("18-24", "18-24"),
                            ("25-34", "25-34"),
                            ("35-44", "35-44"),
                            ("45-54", "45-54"),
                            ("55-64", "55-64"),
                            ("65+", "65+"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "training_age_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("trains_with_me", models.BooleanField(default=False)),
                (
                    "primary_location",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("Gym", "Gym"),
                            ("Outdoor", "Outdoor"),
                        ],
                        default="Gym",
                        max_length=16,
                    ),
                ),
                ("gym_name", models.CharField(blank=True, max_length=120)),
                (
                    "space_available",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Small",
                        max_length=8,
                    ),
                ),
                (
                    "impact_tolerance",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        default="Low",
                        max_length=9,
                    ),
                ),
                ("session_length_min", models.IntegerField(default=60)),
                ("days_per_week", models.IntegerField(default=3)),
                ("preferred_days", models.JSONField(blank=True, default=list)),
                ("goals", models.JSONField(default=list)),
                ("sport_focus", models.CharField(blank=True, max_length=80)),
                ("knee_issue", models.BooleanField(default=False)),
                ("shoulder_issue", models.BooleanField(default=False)),
                ("back_issue", models.BooleanField(default=False)),
                ("injury_notes", models.TextField(blank=True)),
                (
                    "rpe_familiarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("Some", "Some"),
                            ("Comfortable", "Comfortable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("power_interest", models.BooleanField(default=False)),
                ("likes_notes", models.TextField(blank=True)),
                ("dislikes_notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="clients.client",
                    ),
                ),
                ("profile", models.JSONField()),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ClientEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.CharField(
                        choices=[("Home", "Home"), ("Gym", "Gym")], max_length=8
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientInjury",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Knee", "Knee"),
                            ("Shoulder", "Shoulder"),
                            ("Back", "Back"),
                            ("Hip", "Hip"),
                            ("Ankle", "Ankle"),
                            ("Wrist", "Wrist"),
                            ("Neck", "Neck"),
                            ("Elbow", "Elbow"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("severity", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Exercise", "Exercise"),
                            ("Movement Pattern", "Movement Pattern"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=160)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("Like", "Like"),
                            ("Dislike", "Dislike"),
                            ("Hard No", "Hard No"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
